// Generated VS Code package. Evidence class: generated-package checks
// (PACKAGE_TESTED). These show the generator's output is stable, attributed,
// and honest about what is not pinned. They do not show that any host
// discovers or runs it.

import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import { test } from 'node:test';
import { generatePackage, runtimeSources } from '../adapters/copilot-vscode/generate.ts';
import { sha256Hex } from '../core/contracts/records.ts';
import { PACKAGE_ROOT, PROFILE, tmpDir } from './support/harness.ts';

const profileText = readFileSync(PROFILE, 'utf8');

function listFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true, recursive: true })
    .filter((e) => e.isFile())
    .map((e) => relative(dir, join(e.parentPath, e.name)).replaceAll('\\', '/'))
    .sort();
}

function frontmatter(text: string): Record<string, string> {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
  assert.ok(m, 'file starts with frontmatter');
  return Object.fromEntries((m[1] as string).split('\n').map((l) => [l.slice(0, l.indexOf(':')), l.slice(l.indexOf(':') + 1).trim()]));
}

const words = (text: string): number => text.split(/\s+/).filter(Boolean).length;

const AGENT_AND_SKILL_FILES = [
  '.github/agents/rstack-sdlc-coordinator.agent.md',
  '.github/agents/rstack-sdlc-developer.agent.md',
  '.github/agents/rstack-sdlc-plan-auditor.agent.md',
  '.github/agents/rstack-sdlc-planner.agent.md',
  '.github/agents/rstack-sdlc-pr-reviewer.agent.md',
  '.github/agents/rstack-sdlc-reviewer.agent.md',
  '.github/agents/rstack-sdlc-tester.agent.md',
  '.github/skills/rstack-sdlc-application-records/SKILL.md',
  '.github/skills/rstack-sdlc-planning-records/SKILL.md',
];

// The engine and installer sources the two commands reach, and nothing else.
const RUNTIME_FILES = [
  'runtime/adapters/copilot-vscode/install.ts',
  'runtime/adapters/local-pr-proposal/index.ts',
  'runtime/adapters/local-request/index.ts',
  'runtime/adapters/node-test-executor/index.ts',
  'runtime/core/contracts/app.ts',
  'runtime/core/contracts/planning.ts',
  'runtime/core/contracts/ports.ts',
  'runtime/core/contracts/pr-review.ts',
  'runtime/core/contracts/records.ts',
  'runtime/core/contracts/validate.ts',
  'runtime/core/engine/brief.ts',
  'runtime/core/engine/containment.ts',
  'runtime/core/engine/engine.ts',
  'runtime/core/engine/errors.ts',
  'runtime/core/engine/execution.ts',
  'runtime/core/engine/journal.ts',
  'runtime/core/engine/lock.ts',
  'runtime/core/engine/pr-review-packet.ts',
  'runtime/core/engine/proposal.ts',
  'runtime/core/engine/state.ts',
  'runtime/core/engine/tree.ts',
  'runtime/core/policies/pr-review-procedure.ts',
  'runtime/core/policies/workflow.ts',
  'runtime/package.json',
  'runtime/profiles/trial-v2.json',
  'runtime/scripts/assembly.ts',
  'runtime/scripts/install-package.ts',
  'runtime/scripts/rstack.ts',
];

test('the package contains exactly the prefixed agents, the Skills, the runtime it needs, and a manifest', () => {
  const out = join(tmpDir('package'), 'out');
  const manifest = generatePackage({ profileText, outDir: out });
  assert.deepEqual(listFiles(out), [...AGENT_AND_SKILL_FILES, 'rstack-sdlc-manifest.json', ...RUNTIME_FILES]);
  assert.deepEqual(manifest.files.map((f) => f.path), [...AGENT_AND_SKILL_FILES, ...RUNTIME_FILES], 'the manifest lists every file but itself');
  assert.equal(manifest.validation_status, 'UNVERIFIED_ON_HOST');
  // Traceable: generator, profile, extensions definition, and the source of every file.
  assert.deepEqual([manifest.generator, manifest.generator_version, manifest.schema_version], ['rstack-sdlc/adapters/copilot-vscode/generate.ts', 4, 2]);
  assert.deepEqual(manifest.profile, { profile_id: 'trial', profile_version: 2, sha256: sha256Hex(profileText), path: 'runtime/profiles/trial-v2.json' });
  assert.equal(manifest.extensions.source, 'adapters/copilot-vscode/extensions.json');
  assert.equal(manifest.extensions.sha256, sha256Hex(readFileSync(join(PACKAGE_ROOT, 'adapters/copilot-vscode/extensions.json'), 'utf8').replaceAll('\r\n', '\n')));
  for (const f of manifest.files) {
    assert.equal(sha256Hex(readFileSync(join(out, f.path))), f.sha256, `${f.path}: output hash`);
    if (f.kind === 'profile') continue;
    const source = readFileSync(join(PACKAGE_ROOT, f.source), 'utf8').replaceAll('\r\n', '\n');
    assert.equal(sha256Hex(source), f.source_sha256, `${f.path}: source hash`);
    if (f.kind === 'agent' || f.kind === 'skill') {
      assert.ok(readFileSync(join(out, f.path), 'utf8').includes(`GENERATED by rstack-sdlc/adapters/copilot-vscode/generate.ts v4 from ${f.source} (sha256:${f.source_sha256}), profile trial v2`));
    } else if (f.path !== 'runtime/package.json') {
      assert.equal(readFileSync(join(out, f.path), 'utf8'), source, `${f.path}: the runtime file is its source, unchanged`);
    }
  }
});

test('the runtime is what the commands import, the requirements are stated, and nothing else is shipped', () => {
  const out = join(tmpDir('package-runtime'), 'out');
  const manifest = generatePackage({ profileText, outDir: out });
  // Every relative import of a shipped file resolves to a shipped file, so the
  // runtime cannot depend on the checkout it was generated from.
  const shipped = new Set(listFiles(out));
  for (const file of [...shipped].filter((f) => f.endsWith('.ts'))) {
    for (const m of readFileSync(join(out, file), 'utf8').matchAll(/from\s+['"](\.[^'"]+)['"]/g)) {
      const target = relative(out, resolve(out, file, '..', m[1] as string)).replaceAll('\\', '/');
      assert.ok(shipped.has(target), `${file} imports ${target}, which is not in the package`);
    }
  }
  assert.deepEqual(runtimeSources(), RUNTIME_FILES.filter((f) => f.endsWith('.ts')).map((f) => f.slice('runtime/'.length)));
  assert.deepEqual(manifest.engine, { entry: 'runtime/scripts/rstack.ts', installer: 'runtime/scripts/install-package.ts', resolution: 'INSTALL_TIME_ABSOLUTE_PATH' });
  // Node is required and not bundled; the package does not claim to be self-contained.
  const nodeRange = (JSON.parse(readFileSync(join(PACKAGE_ROOT, 'package.json'), 'utf8')) as { engines: { node: string } }).engines.node;
  assert.deepEqual(manifest.runtime_requirements, { node: nodeRange, bundled: false, third_party_packages: 'none' });
  assert.deepEqual(JSON.parse(readFileSync(join(out, 'runtime/package.json'), 'utf8')), { name: 'rstack-sdlc-runtime', private: true, type: 'module', engines: { node: nodeRange } });

  // Excluded: evidence, baselines, evaluations, build guidance, tests, the generator,
  // test adapters, deferred integrations, and anything of the previous pipeline.
  const forbidden = /(^|\/)(\.baselines|\.rstack|evals|evaluation|docs|tests|node_modules|dist|fake-transport|fake-file-drop-transport|jira|bitbucket|rstack-pipeline)(\/|$)|generate\.ts$|generate-package\.ts$|synthetic-run\.ts$|evaluate\.ts$|README|FACTORY-CONTRACT|BATCHES-AND-EVALS|MODELS-AND-STUBS|\.gitignore|package-lock/;
  for (const file of shipped) assert.doesNotMatch(file, forbidden, file);
  // No file carries a path of the machine it was generated on.
  const home = PACKAGE_ROOT.split(sep).slice(0, 3).join(sep);
  for (const file of shipped) {
    const text = readFileSync(join(out, file), 'utf8');
    for (const needle of [PACKAGE_ROOT, PACKAGE_ROOT.replaceAll('\\', '/'), home, home.replaceAll('\\', '/')]) {
      assert.ok(!text.includes(needle), `${file} contains a local path`);
    }
  }
  // The engine command is a placeholder until installation; no relative guess is written.
  const coordinator = readFileSync(join(out, '.github/agents/rstack-sdlc-coordinator.agent.md'), 'utf8');
  assert.match(coordinator, /\{\{ENGINE\}\} start --workspace \{\{WORKSPACE\}\} --profile \{\{PROFILE\}\} --app/);
  assert.doesNotMatch(coordinator, /node rstack-sdlc\/|--workspace \./);
  assert.deepEqual(manifest.install_tokens, ['ENGINE', 'WORKSPACE', 'PROFILE', 'RUN_ROOT']);
});

test('generating twice from the same inputs gives identical bytes', () => {
  const base = tmpDir('package-twice');
  const digest = (dir: string): string => listFiles(dir).map((f) => `${f}:${sha256Hex(readFileSync(join(dir, f)))}`).join('\n');
  generatePackage({ profileText, outDir: join(base, 'a') });
  generatePackage({ profileText, outDir: join(base, 'b') });
  assert.equal(digest(join(base, 'a')), digest(join(base, 'b')));
  // Regenerating over an existing output replaces it without leaving stale files.
  generatePackage({ profileText, outDir: join(base, 'a') });
  assert.equal(digest(join(base, 'a')), digest(join(base, 'b')));
});

test('MODEL-1: an unobserved selector is never written as a pinned model, and no effort key exists', () => {
  const out = join(tmpDir('package-model'), 'out');
  const manifest = generatePackage({ profileText, outDir: out });
  for (const file of listFiles(out).filter((f) => f.endsWith('.agent.md'))) {
    const text = readFileSync(join(out, file), 'utf8');
    const keys = Object.keys(frontmatter(text));
    assert.ok(!keys.includes('model'), `${file}: no model key`);
    assert.ok(!keys.some((k) => /effort|reasoning/i.test(k)), `${file}: no effort key`);
    assert.match(text, /Model not pinned\. Intended for this role: (Opus 5\.5|Sonnet 5|Sol 6\.1)/);
  }
  assert.deepEqual(
    Object.fromEntries(Object.entries(manifest.models).map(([role, m]) => [role, [m.owner_label, m.model_key, m.selector_status]])),
    {
      coordinator: ['Sonnet 5', 'OMITTED', 'requires-host-observation'],
      planner: ['Opus 5.5', 'OMITTED', 'requires-host-observation'],
      'plan-auditor': ['Sol 6.1', 'OMITTED', 'requires-host-observation'],
      tester: ['Sonnet 5', 'OMITTED', 'requires-host-observation'],
      developer: ['Sonnet 5', 'OMITTED', 'requires-host-observation'],
      reviewer: ['Opus 5.5', 'OMITTED', 'requires-host-observation'],
      'pr-reviewer': ['Opus 5.5', 'OMITTED', 'requires-host-observation'],
    },
  );

  // Only a selector recorded as observed is written, and exactly as recorded.
  const observed = JSON.parse(profileText) as Record<string, any>;
  observed.catalog.opus = { ...observed.catalog.opus, host_selector: 'EXAMPLE SELECTOR (test only)', selector_status: 'observed' };
  const pinned = generatePackage({ profileText: JSON.stringify(observed), outDir: out });
  assert.equal(pinned.models.planner?.model_key, 'WRITTEN');
  assert.equal(frontmatter(readFileSync(join(out, '.github/agents/rstack-sdlc-planner.agent.md'), 'utf8')).model, 'EXAMPLE SELECTOR (test only)');
  assert.ok(!('model' in frontmatter(readFileSync(join(out, '.github/agents/rstack-sdlc-plan-auditor.agent.md'), 'utf8'))));
});

test('agents use documented frontmatter keys; workers are hidden and only the coordinator may delegate', () => {
  const out = join(tmpDir('package-front'), 'out');
  generatePackage({ profileText, outDir: out });
  const documented = new Set(['name', 'description', 'target', 'tools', 'agents', 'user-invocable', 'disable-model-invocation', 'model']);
  const read = (role: string): Record<string, string> => frontmatter(readFileSync(join(out, `.github/agents/rstack-sdlc-${role}.agent.md`), 'utf8'));
  for (const role of ['coordinator', 'planner', 'plan-auditor', 'tester', 'developer', 'reviewer', 'pr-reviewer']) {
    const fm = read(role);
    for (const key of Object.keys(fm)) assert.ok(documented.has(key), `${role}: undocumented key ${key}`);
    assert.equal(fm.name, `rstack-sdlc-${role}`);
  }
  assert.equal(read('coordinator').agents, "['rstack-sdlc-planner', 'rstack-sdlc-plan-auditor', 'rstack-sdlc-tester', 'rstack-sdlc-developer', 'rstack-sdlc-reviewer', 'rstack-sdlc-pr-reviewer']");
  for (const role of ['planner', 'plan-auditor', 'tester', 'developer', 'reviewer', 'pr-reviewer']) {
    assert.equal(read(role)['user-invocable'], 'false');
    assert.ok(!read(role).tools?.includes('agent'), `${role} cannot delegate`);
  }
  assert.ok(!read('reviewer').tools?.includes('execute'), 'the reviewer has no terminal');
  assert.equal(read('pr-reviewer').tools, read('reviewer').tools, 'the PR reviewer has the code reviewer\'s tool sets and no more');
  assert.equal(read('coordinator').tools, "['execute', 'read', 'agent']");
  for (const role of ['planner', 'plan-auditor']) {
    assert.equal(read(role)['user-invocable'], 'false');
    assert.ok(!read(role).tools?.includes('agent'), `${role} cannot delegate`);
    assert.ok(!read(role).tools?.includes('execute'), `${role} has no terminal`);
    assert.ok(!('agents' in read(role)));
  }
  const skill = readFileSync(join(out, '.github/skills/rstack-sdlc-planning-records/SKILL.md'), 'utf8');
  assert.equal(frontmatter(skill).name, 'rstack-sdlc-planning-records', 'Skill name equals its directory name');
  assert.ok((frontmatter(skill).description as string).length <= 1024);
  // Descriptions contain ": ", so they are quoted to keep the frontmatter valid YAML.
  for (const file of listFiles(out).filter((f) => f.endsWith('.md'))) {
    assert.match(frontmatter(readFileSync(join(out, file), 'utf8')).description as string, /^'[^']+'$/, file);
  }
});

test('authored instructions stay within the project review budgets', () => {
  for (const file of ['core/roles/planner.md', 'core/roles/plan-auditor.md', 'core/roles/tester.md', 'core/roles/developer.md', 'core/roles/reviewer.md', 'adapters/copilot-vscode/coordinator.md']) {
    const n = words(readFileSync(join(PACKAGE_ROOT, file), 'utf8'));
    assert.ok(n < 1000, `${file}: ${n} words`);
  }
  for (const file of ['core/skills/planning-records/SKILL.md', 'core/skills/application-records/SKILL.md']) {
    const n = words(readFileSync(join(PACKAGE_ROOT, file), 'utf8'));
    assert.ok(n < 1500, `${file}: ${n} words`);
  }
});

test('RETRIEVAL-1: every format rule the engine enforces is present in the Skill the roles are pointed to', () => {
  const skill = readFileSync(join(PACKAGE_ROOT, 'core/skills/planning-records/SKILL.md'), 'utf8');
  for (const needed of ['Open decisions:', 'AC-1:', '"record_type": "plan"', '"record_type": "audit-result"', '"record_type": "finding-dispositions"', 'Exactly one entry per finding', 'HOLDS', 'REFUTED', 'INCONCLUSIVE', 'NOT_CHECKED', 'must have `evidence`']) {
    assert.ok(skill.includes(needed), `Skill lacks: ${needed}`);
  }
});

test('SCOPE-1: the generator refuses to write outside the package or into its sources', () => {
  const repoRoot = resolve(PACKAGE_ROOT, '..');
  for (const outDir of [join(repoRoot, '.github'), join(repoRoot, '.vscode'), repoRoot, join(PACKAGE_ROOT, 'core'), join(PACKAGE_ROOT, 'adapters', 'x'), PACKAGE_ROOT]) {
    assert.throws(() => generatePackage({ profileText, outDir }), /refusing to generate/, outDir);
  }
});
